### ISSUE TITLE
Not finding RAW data tab in any of the Navajo ploygon file data in git hub

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#21]

**Comment by jonathanwheeler01** [comment]
It looks like github changed "raw" to a pair of brackets "<>." If you click that, you will likely also have to click the link "View Raw" because the files are big.

For Navajo raw/geojson, try:

https://raw.githubusercontent.com/nawrs/nawrs/GeoJSON/JSON/IndividualTribalPolygons/Navaj.geojson

https://raw.githubusercontent.com/nawrs/nawrs/GeoJSON/JSON/IndividualTribalPolygons/NavTr.geojson

https://raw.githubusercontent.com/nawrs/nawrs/GeoJSON/JSON/IndividualTribalPolygons/Navaj.geojson

**Comment by dmc793** [comment]
Thanks.  That file is huge.  Does it matter which one I use? d

**Comment by jonathanwheeler01** [comment]
"Navaj" is the complete geometry, the other two have been split, I guess the reduce the size. Simplest approach seems to be to use "Navaj" since that's the only one that can stand alone.

It should be fine going into Digital Commons, but may cause slowness in the mapper. If that happens we can implement an alternative solution.

Thanks!

**Comment by dmc793** [comment]
So I have figured this one out. We need the complete geometry to show on the map and the one in NM.  That one is the only one has documents at this time.  The other  geometry probably relate to those areas of the Rez that are in Az & Utah.  They will eventually have documents and will need to be split by state.

**Comment by jonathanwheeler01** [comment]
Going to close this - please let me know if additional action is needed.

**Comment by dmc793** [comment]
Looking good
